import json
from src.tools.registry import search_information, retrieve_document, calculate_metric

class ToolDispatcher:
    def __init__(self):
        self.handlers = {
            "search_information": search_information,
            "retrieve_document": retrieve_document,
            "calculate_metric": calculate_metric
        }

    def dispatch(self, tool_name: str, arguments_json: str):
        if tool_name not in self.handlers:
            return {"error": f"Unknown tool: {tool_name}"}
        
        try:
            args = json.loads(arguments_json)
        except json.JSONDecodeError:
            return {"error": "Invalid JSON arguments generated by model."}
            
        try:
            handler = self.handlers[tool_name]
            result = handler(**args)
            return {"status": "success", "data": result}
        except Exception as e:
            return {"error": f"Tool execution error: {str(e)}"}